### ISSUE TITLE
Full resolution image visualization based on ground turth illuminant is different from camera raw/jpg image

### ISSUE THREAD

**Issue by wxy1234567** [huawei-noah/multi_hyp_cc#15]
Thank you for your excellent work!

When I reproduce the code, I find that full resolution image visualization based on ground turth illuminant is different from camera raw image.

**Comment by dhernandez0** [comment]
Thanks for your feedback! Please, could you provide images to understand the issue? 

It sounds like the issue is the difference between our generated image and the camera JPG. That's expected because the camera JPG goes through the full ISP, and our final image is a very simplified ISP: https://github.com/huawei-noah/multi_hyp_cc/blob/426b221eb466996f02a8c2ae62919e675e50436f/core/display.py#L211

**Comment by wxy1234567** [comment]
Thank you for your reply, which solved my question.
